package com.plopez.diceroller.microservice.player.model.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class PlayerDTO {

    @NotNull(message = "Id must not be null.")
    @JsonIgnore
    @Schema(description = "Entity identification. It is autogenerated.", example = "1")
    private int id;
    @Schema(description = "Entity nickname identification. When it is sent as empty or in blank, the service turn it as 'Anonymous'.", example = "playerNickName", requiredMode = Schema.RequiredMode.REQUIRED)
    @NotNull(message = "Nickname must not be null.")
    private String nickname;
    @Schema(description = "Entity creation time stamp. It is autogenerated.", example = "playerNickName")
    private LocalDateTime registrationTimeStamp;
    @Schema(description = "Success average of all the games played by the player. It is autogenerated after the game is created (aka 'played').", example = "playerNickName")
    private float gameSuccessRate;
}
